### ISSUE TITLE
Explainabililty 

### ISSUE THREAD

**Issue by Miriam2040** [yuval-alaluf/Attend-and-Excite#30]
Can the explain notebook work for real images that weren't created by Attend and Excite or Stable Diffusion?

I tried:
image = Image.open("turtle.jpg")
vis_utils.show_cross_attention(attention_store=controller,
                                   prompt=prompt,
                                   tokenizer=tokenizer,
                                   res=16,
                                   from_where=("up", "down", "mid"),
                                   indices_to_alter=token_indices,
                                   orig_image=image)

And got error:
│ in <cell line: 5>:5                                                                              │
│                                                                                                  │
│ /content/Attend-and-Excite/utils/vis_utils.py:22 in show_cross_attention                         │
│                                                                                                  │
│   19 │   │   │   │   │   │    orig_image=None):                                                  │
│   20 │   tokens = tokenizer.encode(prompt)                                                       │
│   21 │   decoder = tokenizer.decode                                                              │
│ ❱ 22 │   attention_maps = aggregate_attention(attention_store, res, from_where, True, select)    │
│   23 │   images = []                                                                             │
│   24 │                                                                                           │
│   25 │   # show spatial attention for indices of tokens to strengthen                            │
│                                                                                                  │
│ /content/Attend-and-Excite/utils/ptp_utils.py:228 in aggregate_attention                         │
│                                                                                                  │
│   225 │   attention_maps = attention_store.get_average_attention()                               │
│   226 │   num_pixels = res ** 2                                                                  │
│   227 │   for location in from_where:                                                            │
│ ❱ 228 │   │   for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"]:       │
│   229 │   │   │   if item.shape[1] == num_pixels:                                                │
│   230 │   │   │   │   cross_maps = item.reshape(1, -1, res, res, item.shape[-1])[select]         │
│   231 │   │   │   │   out.append(cross_maps)                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'up_cross'

**Comment by yuval-alaluf** [comment]
If you're trying to get an explainability map on real images, I would use a different approach.
A good go to is https://github.com/hila-chefer/Transformer-MM-Explainability from @hila-chefer.
