### ISSUE TITLE
Prompts for the quantitative results

### ISSUE THREAD

**Issue by truongvu2000nd** [yuval-alaluf/Attend-and-Excite#31]
Could you please release the list of prompts used for the evaluations in the paper? Thanks.

**Comment by hila-chefer** [comment]
Hi @truongvu2000nd, thanks for your interest!
Please see [this issue](https://github.com/yuval-alaluf/Attend-and-Excite/issues/17), where we attached the list of prompts.

**Comment by truongvu2000nd** [comment]
Thank you very much
