### ISSUE TITLE
How to visualize the cross-attention map of each token

### ISSUE THREAD

**Issue by youngwanLEE** [yuval-alaluf/Attend-and-Excite#33]
Hi, I'm really impressed by your work.

I wonder how to visualize the cross-attention of each token as in Fig.3 of your paper?

Thanks in advance :)

**Comment by hila-chefer** [comment]
Hi @youngwanLEE, thanks for your interest and kind words!
The visualizations in Fig. 3 were obtained using the [prompt-to-prompt code base](https://github.com/google/prompt-to-prompt/blob/main/prompt-to-prompt_stable.ipynb) (see Cross-Attention Visualization in the referenced notebook).
We also provided a [notebook](https://github.com/yuval-alaluf/Attend-and-Excite/blob/main/notebooks/explain.ipynb) to obtain heatmaps similar to Fig. 4 of the paper.

**Comment by youngwanLEE** [comment]
Thanks!
