### ISSUE TITLE
About the Memory usage

### ISSUE THREAD

**Issue by huan085128** [yuval-alaluf/Attend-and-Excite#34]
Very interesting work. But I noticed that generating 512 resolution images requires about 16GB of memory, and generating 1024 images exceeds 80GB, so that it cannot run on A100. I checked the pipeline code and found that calling unet multiple times in the denoising loop caused a lot of memory consumption. Can this be further optimized?

**Comment by yuval-alaluf** [comment]
This could probably be optimized, with the simplest solution being using FP16 for inference. 
I have seen various people working on optimizing the memory requirements for Stable Diffusion using diffusers, so you may be able to use some of those tricks (although I don't have a specific link to share with you). 
If you want to dive into the diffusers code a bit, you could try seeing where exactly the peak in memory comes from and try to see how to mitigate that.
Hope this helps a bit.

**Comment by huan085128** [comment]
> This could probably be optimized, with the simplest solution being using FP16 for inference. I have seen various people working on optimizing the memory requirements for Stable Diffusion using diffusers, so you may be able to use some of those tricks (although I don't have a specific link to share with you). If you want to dive into the diffusers code a bit, you could try seeing where exactly the peak in memory comes from and try to see how to mitigate that. Hope this helps a bit.


Thank you for your reply. I noticed that the most memory-consuming part is the CrossAttnProcessor calculating the attention scores. This part could originally use xformers to save memory, but xformers seems to be unable to be used for calculating attention scores.

**no xformers**

> attention_probs = attn.get_attention_scores(query, key, attention_mask)
self.controller(attention_probs, is_cross, self.place_in_unet)
hidden_states = torch.bmm(attention_probs, value)

**with xoformers**

> hidden_states = xformers.ops.memory_efficient_attention(
            query, key, value, attn_bias=attention_mask, op=self.attention_op)
