### ISSUE TITLE
perhaps you can be an add-in for sdwebui?

### ISSUE THREAD

**Issue by ccartermices** [yuval-alaluf/Attend-and-Excite#36]

**Comment by hila-chefer** [comment]
Hi @ccartermices, thanks for your interest!

please refer to [this issue](https://github.com/yuval-alaluf/Attend-and-Excite/issues/20) for more details about a webui implementation. We currently do not plan to support webui, however there’s an open issue in the repo to incorporate our method.

I hope this helps.
