### ISSUE TITLE
Did you release the evaluation dataset in your paper?

### ISSUE THREAD

**Issue by YasminZhang** [yuval-alaluf/Attend-and-Excite#37]
As title. The dataset mentioned in the paper includes animal, object and colors.

**Comment by hila-chefer** [comment]
Hi @YasminZhang, thanks for your interest!

please refer to [this issue](https://github.com/yuval-alaluf/Attend-and-Excite/issues/17) where we attached our full list of prompts for evaluation.

**Comment by YasminZhang** [comment]
> Hi @YasminZhang, thanks for your interest!
> 
> please refer to [this issue](https://github.com/yuval-alaluf/Attend-and-Excite/issues/17) where we attached our full list of prompts for evaluation.

Thanks a lot!
