### ISSUE TITLE
Comfyui

### ISSUE THREAD

**Issue by rainsoulsrx** [yuval-alaluf/Attend-and-Excite#38]
Will you plan to support comfyui?

**Comment by hila-chefer** [comment]
Hi @rainsoulsrx, thanks for your interest!
We currently do not plan to support comfyui, however, our method if fully supported by the [diffusers library](https://huggingface.co/docs/diffusers/api/pipelines/attend_and_excite), so anything compatible with diffusers should be easily adaptable.
I hope this helps.

**Comment by rainsoulsrx** [comment]
Will you support SDXL

**Comment by hila-chefer** [comment]
The current pipeline on diffusers does not seem support SDXL out of the box but the adaptations shouldn’t be too hard to make. We currently do not plan to add support for SDXL from this repo.
